[font]
size = 14.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" } 
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" } 

[window]
# dimensions = { x = 125, y = 40 }
opacity = 0.9
blur = true
title = "Terminal (Alacritty)"

[bell]
animation = "Ease"
duration = 1
