"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch
$character(bold green)"""

add_newline = false

[character]
success_symbol = "[❯](bold green)"

[username]
style_user = "green bold"
style_root = "red bold"
format = "[$user]($style) in "
disabled = false
show_always = true
